### ISSUE TITLE
Inconsistent syntax for arg tag in XML launch

### ISSUE THREAD

**Issue by mjforan** [ros2/launch#720]
## Bug report

**Required Info:**

- Operating System:
  - Ubuntu 22.04
- Installation type:
  - Humble
  - Binaries
  - ros-humble-desktop/jammy,now 0.10.0-1jammy.20230624.051647 amd64

#### Steps to reproduce issue
Example section of XML launch file for starting Gazebo simulator

```
<arg name="world_name"      default="warehouse"/>  <!-- world name -->
<!-- Launch Ignition Gazebo --> 
<include file="/launch/ign_gazebo.launch.py">
    <arg name="ign_args" value="/config/worlds/$(var world_name).sdf $(var use_levels)"/>
</include>
```

#### Expected behavior
According to [the launch migration guide](http://docs.ros.org/en/rolling/How-To-Guides/Launch-files-migration-guide.html?highlight=value#arg), `<arg>` should be used with `default` and `<let>` should be used with `value`. However, When `arg` is nested under an `include` tag it is necessary to use the `value` instead. You can see in the example how `arg` has two different syntaxes, depending on the context.

#### Actual behavior
Attempting to use the suggested syntax triggers the following error:
```
Caught exception when trying to load file of format [xml]: Attribute value of type <class 'str'> not found in Entity arg
```

**Comment by denseishin** [comment]
I'm experiencing the same under Ubuntu 24.04 & ROS2 Jazzy

**Comment by christophebedard** [comment]
This is still the case today in all distros. I was also surprised by this when I worked on https://github.com/ros2/ros2_documentation/pull/5104.

The simple answer is that the code indeed expects `<arg>` entities with `name` and `value` attributes, but it doesn't actually parse them (using `parser.parse_action(e) for e in entity.children`, otherwise they would be actual `<arg>`/`DeclareLaunchArgument` actions): https://github.com/ros2/launch/blob/6fcc79e38fa711e04be3d392a6691a36ea5de214/launch/launch/actions/include_launch_description.py#L91-L101. It then creates `SetLaunchConfiguration` actions from those, which are equivalent to the frontend's `let` action, not `arg` (`DeclareLaunchArgument`): https://github.com/ros2/launch/blob/6fcc79e38fa711e04be3d392a6691a36ea5de214/launch/launch/actions/include_launch_description.py#L187-L188.

Examples: https://docs.ros.org/en/rolling/Tutorials/Intermediate/Launch/Using-Substitutions.html#parent-launch-file

<details>
<summary>XML</summary>

```xml
<launch>
  <let name="background_r" value="200"/>
  <include file="$(find-pkg-share launch_tutorial)/launch/example_substitutions_launch.xml">
    <arg name="turtlesim_ns" value="turtlesim2" />
    <arg name="use_provided_red" value="True" />
    <arg name="new_background_r" value="$(var background_r)" />
  </include>
</launch>
```

</details>

<details>
<summary>YAML</summary>

```yaml
launch:
  - let:
      name: 'background_r'
      value: '200'
  - include:
      file: '$(find-pkg-share launch_tutorial)/launch/example_substitutions_launch.yaml'
      arg:
        - name: 'turtlesim_ns'
          value: 'turtlesim2'
        - name: 'use_provided_red'
          value: 'True'
        - name: 'new_background_r'
          value: '$(var background_r)'
```

</details>

Now as to why it does this, I believe it's because ROS 1's launch XML `<include>` used `<arg>`: https://wiki.ros.org/roslaunch/XML/include#Elements. ROS 1 also [didn't have `<let>`](https://docs.ros.org/en/rolling/How-To-Guides/Migrating-from-ROS1/Migrating-Launch-Files.html#let).

I think it could probably simply also accept `<let>`.
